### ISSUE TITLE
Log in button goes away for unauthenticated users

### ISSUE THREAD

**Issue by eyuelt** [tessa3/uxgraph#113]
Even if you're not logged in, `userLoggedIn` in `home.component.ts` still gets set to `true`, so the log in button, goes away and shows and empty list of uxgraphs. This is probably because our call to `gapi.auth.authorize` is doing something wrong. I wanted to fix this, but couldn't find the documentation for the old GAPI auth library. @girum11 can you link me to the documentation you were using?

**Comment by girum11** [comment]
@eyuelt here's the Quickstart guide for the version of gapi I wired up:
https://developers.google.com/drive/v3/web/quickstart/js

**Comment by girum11** [comment]
I've added this to part of [Harden the Google Realtime API](https://github.com/tessa3/uxgraph/milestone/14)
