### ISSUE TITLE
Build a client-side demo with zoom and pan.

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#21]
Prototype a way for us to interact with our canvas, according to spec. Draw a single MD card on the screen, and build the demo to be able to pan and zoom around that card. Enforce a minimum and maximum zoom distance.

Will you [use D3 to implement zoom](https://bl.ocks.org/mbostock)? Maybe [another library](https://github.com/ariutta/svg-pan-zoom)? 

Don't worry yet about it playing well with Angular, we'll figure that out later based on your approach on this demo.

**Comment by eyuelt** [comment]
[Demo with zoom and pan](https://jsfiddle.net/eyuelt/35c4Lzjg/)

**Comment by girum11** [comment]
This looks and feels amazing. Great job so far!



Currently, you scale the circles so that they're the same size to the user at all times. Can you change the circles to adjust size proportional to the current zoom level?

**Comment by eyuelt** [comment]
[Relevant](https://media.giphy.com/media/ToMjGpMhVjTvjX5nLs4/giphy.gif)

Yup, just uncomment line 46.

**Comment by girum11** [comment]
Very very cool, awesome work. If we can combine the original scaling of the screen cards with semantic zoom of their contents, I'd be very happy  👍
