### ISSUE TITLE
Confirm that Google Realtime API supports unauthenticated users

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#22]
It's not clear from quick glances whether or not [Google's Realtime API](https://developers.google.com/google-apps/realtime/overview) that we want to build on top of supports unauthenticated users. We want users to be able to:

- type in "uxgraph.io" in Incognito mode and immediately be able to create a new uxgraph without logging into Google
- if the unauthenticated user remembers the URL he had, he should be able to open up the same later
- if the unauthenticated user has the URL to someone else's uxgraph, he should be able to open that up too (if he has permission to view)

Once you confirm that the Realtime API supports these use cases, this issue is done. 

In the event that Realtime API does *not* support these use cases, we'll have to investigate switching to another system like Firebase...

**Comment by nati22** [comment]
Going to continue to investigate, but I'll leave [this](https://developers.google.com/google-apps/realtime/faq#do_my_users_need_google_accounts) here for now...

**Comment by eyuelt** [comment]
You can use the API in [in-memory mode](https://developers.google.com/google-apps/realtime/in-memory) while unauthenticated, which means the collaboration won't work, but you can still create a document, modify it, and serialize it out. Which means we'd have to have our own server for storing this data. This [quickstart](https://developers.google.com/google-apps/realtime/realtime-quickstart) has an example.

So we can support use cases 1 and 2. We can also support some version of 3, if we're cool with it just being a view-only snapshot. But this would mean we'd have to store snapshots of all shared docs on our own servers.

**Comment by nati22** [comment]
Does case 3 even make sense? How can an unauthenticated user receive permission to view a doc?

**Comment by nati22** [comment]
The owner of the uxgraph would have to make it public to everyone

**Comment by eyuelt** [comment]
Yeah, if the doc is public, then unauthorized users should be able to see it too.

**Comment by nati22** [comment]
Looks like all @tessa3/owners are satisfied with Realtime's "in-memory mode" support for unauthenticated users so I'm closing this issue.
