### ISSUE TITLE
Confirm that Google Realtime API supports Drive's sharing model

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#23]
Consider the following user story across users Alice and Bob:

- Alice creates a new uxgraph and does not share it with Bob.
- Bob (somehow) gets a hold of Alice's uxgraph URL.
- Bob goes to Alice's URL
- Bob should not be able to see Alice's uxgraph, and instead sees a permission warning

In this situation, we should allow both cases:
1. Bob should be able to request permission from the uxgraph's owner
2. Alice should be able to type in Bob's name and grant Bob permission.

Confirm that the [Google Realtime API](https://developers.google.com/google-apps/realtime/overview) supports this use-case.

**Comment by eyuelt** [comment]
[Realtime API Collaboration Guide](https://developers.google.com/google-apps/realtime/collaborators)
[Google Drive Permissions and Sharing Guide](https://developers.google.com/drive/v3/web/manage-sharing)

Yup, for the most part, it does.

I don't think it supports requesting permission out of the box, as I don't see anything about it in the [API Reference](https://developers.google.com/drive/v3/reference/permissions). But we can roll it up on our own without much trouble.

Of course, this doesn't handle unauthed users. It should be doable based on how we handle unauthed users but that's outside the scope of this issue.

**Comment by eyuelt** [comment]
So the two things we'll need to implement on our own are requesting permission and sharing with unauthenticated users when a document is made public.
