### ISSUE TITLE
Make sure our Travis build can break

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#26]
Clone our repo and make a tiny little PR that causes one of the out-of-the-box JS Jasmine/Karma unit tests to fail an expectation (.spec.js files). Confirm that this tiny PR with failing unit tests causes our build to break.

Repeat this exercise, but check to see if a TypeScript error also causes the Travis build to break (not just a failing assert).

**Comment by nati22** [comment]
Got Travis build number 67 to break
