### ISSUE TITLE
Change Travis builds to deploy to dev.uxgraph.io

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#28]
Right now, our app lives on http://tessa3-uxgraph.appspot.com/.

Let's switch this to https://staging.uxgraph.io:
https://cloud.google.com/appengine/docs/python/console/using-custom-domains-and-ssl

Later we can introduce a fancy button that deploys staging -> production.

**Comment by nati22** [comment]
I think you'll have to add uxgraph.io as a custom domain, @girum11

**Comment by girum11** [comment]
Google Domains appears to have a dead simple UI integration with Google App Engine. I think I've wired up our "tessa3-uxgraph" App Engine project to "staging.uxgraph.io", but it says that the DNS servers may need up to 24 hours to show changes.

Let's see if it worked!

**Comment by nati22** [comment]
:+1:

**Comment by girum11** [comment]
http://dev.uxgraph.io/
