### ISSUE TITLE
Set up Angular 2 version of "Hello world" on our project.

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#3]

**Comment by girum11** [comment]
https://angular.io/ for Angular 2, not Angular 1.

Just get a proper index.html working and serve up the angular.js file. Use it to render a template expression for "Hello world."

**Comment by nati22** [comment]
First commit is at 9ea4cc7b6d280b36753c9e802a5b83cfef1c1a3e. Haven't been able to deploy to GAE yet though :/

**Comment by nati22** [comment]
Just to keep a record here, this issue is dependent on #4 because GAE Launcher fails to deploy the entire repo since there are wayy too many files in /node_modules

**Comment by nati22** [comment]
#4 is done so I guess this is done too. It's more than a simple Hello World though, it's the seed project from https://github.com/mgechev/angular2-seed
