### ISSUE TITLE
Wire up LGTM.co for PR approvals

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#30]
Right now, anyone can push anything to master at any time. This works for now, but at some point we'll want to formalize Pull Request approvals.

Let's use LGTM.co (or something similar) to add PR approval to our commit pipeline.

As part of this, we'll have to decide how many "LGTM"s are needed before we can push to master. We can go with "need both LGTMs," but I somehow don't trust Eyuel to actually check his computer...

**Comment by eyuelt** [comment]
That was one time! But I think one LGTM should be enough.

**Comment by nati22** [comment]
LGTM is up and running successfully
