### ISSUE TITLE
Create Card component

### ISSUE THREAD

**Issue by eyuelt** [tessa3/uxgraph#35]
Create an angular component that draws a card on the SVG canvas.

**Comment by eyuelt** [comment]
The Card component will handle rendering the card, but there should also be a CardModel class that the Card uses as it's model. (class names TBD)

**Comment by girum11** [comment]
I'd probably reverse the naming a bit. I'd probably say something more like "CanvasRenderer" for the logic you [built in the demo](https://jsfiddle.net/eyuelt/35c4Lzjg/) and "Card" for [the model API](https://en.wikipedia.org/wiki/Domain-driven_design) that wraps our raw data.
