### ISSUE TITLE
Restrict "master" to only be able to commit after LGTM

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#36]
... but!

There should be a way to force push in case of emergency.

**Comment by nati22** [comment]
Or for trivial changes?

**Comment by girum11** [comment]
Yup

**Comment by nati22** [comment]
Actually, the easiest way to implement this would be to allow the PR creator to LGTM their own PR, and we'd only do so for the emergency/trivial case. Thoughts?

**Comment by eyuelt** [comment]
Does that work? If so, 👍.

**Comment by girum11** [comment]
Mm, lgtm.co might not support this. If it does, we should separate "trivial CL, so I LGTM'd it myself"  cases from "it was an emergency, I force pushed" cases.

**Comment by nati22** [comment]
Lgtm.co supports it, there's a config variable called "self_approval_off". They also let you define custom regex patterns which trigger LGTM approval so we can have "LGTM", "TRIVIAL" or whatever else we like.

**Comment by girum11** [comment]
SGTM, let's do something like "LGTM" and "TRIVIAL" like you're saying.

**Comment by nati22** [comment]
STGY @eyuelt?

**Comment by eyuelt** [comment]
So LGTM for an actual approval, TRIVIAL for a trivial fix, and FORCE if it's an emergency? And how do we make sure that the trivial change is actually trivial? Is trivial just for UI changes?

**Comment by nati22** [comment]
Hmm. Good question. And what if someone's only touching Sketch files?

**Comment by girum11** [comment]
I'm okay with going through LGTM to merge "design-work" into "master" only after design reviews.

**Comment by nati22** [comment]
So the standing question is how we enforce whether something is TRIVIAL or not. I guess that can just be a judgement call?

**Comment by girum11** [comment]
Yeah let's keep this a judgment call for now. We can always change our minds later.
