### ISSUE TITLE
Remove angular2-seed and re-implement an Angular 2 solution from scratch

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#37]
@eyuelt isn't very keen on consuming a seed project that we don't all understand fully. Let's revert the contents of [that commit](https://github.com/tessa3/uxgraph/commit/62a022c798383c7572c3740325d11ecdff04a8fb).

Instead, let's pick up where @nati22 left off: @eyuelt should finish integrating Gulp with Google App Engine (deployed via Travis) with a manual Angular 2 "Hello, World!" project.

When it's all done and working, send a giant PR our way so we can re-deploy to our *.appspot.com domain.

**Comment by eyuelt** [comment]
We've decided to stick with the seed project for now.
