### ISSUE TITLE
Set up automatic minification, concatenation and transpilation through Gulp

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#4]
http://gulpjs.com/

Mostly, follow the official TypeScript through Gulp tutorial:
https://www.typescriptlang.org/docs/handbook/gulp.html

Set up a gulpfile that automatically does at least the following:

- Minifiation (through [uglifyjs2](https://github.com/mishoo/UglifyJS2))
- Concatenation (through the generated RequireJS modules being auto-concatenated by Browserify, same as the tutorial does)
- Transpilation (TS -> JS, obviously)

Once you have all of these files being autogenerated by Gulp, you'll be able to change your index.html to point to the 2 autogenerated .js output files:

1. Let's call this one `lib.js` for all the JS library code
2. Let's call this one `app.js` for our actual JS app code.

You'll be able to safely change your index.html to point to those two files even though they don't exist because Gulp guarantees that it'll generate them for you  :)

Once you finish that, you're QED for this ticket.

**Comment by nati22** [comment]
Spent almost an hour trying to debug issues with tsify in the Gulp tutorial. @eyuelt took a look at it as well. I'll try to coming back to it tomorrow

**Comment by girum11** [comment]
I'm unsure of what's causing that build, but it seems like we're probably doing too much work for this ticket.

Let's start our client-side "Hello World" over again off of an existing seed project that thousands of other developers are also basing their work off of:
https://github.com/mgechev/angular2-seed

Then we can go backwards and deploy it to App Engine using your existing code.

**Comment by nati22** [comment]
So I've got Travis deploying the app to GAE but the default angular2-seed project is looking for minified assets inside the node_modules dir (which isn't on the GAE server). You can see this at http://tessa3-uxgraph.appspot.com/. I'm guessing I'll need to incorporate Browserify in some way to fix this issue but I'm not quite sure which approach yet.

**Comment by nati22** [comment]
Finally got it working

**Comment by girum11** [comment]
Nicely done.
