### ISSUE TITLE
Write our first Jasmine/Karma "Hello World" unit test

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#5]
Follow the directions in the official Angular 2 testing documentation:
https://angular.io/docs/ts/latest/guide/testing.html

Wire up Travis to automatically run these tests just like it's currently running our Python test(s).

This ticket (probably) requires Gulp to be configured.

**Comment by nati22** [comment]
Jasmine is already set-up by the [angular2-seed](https://github.com/mgechev/angular2-seed) project we're using 👍
