### ISSUE TITLE
Build the FAB into the Graph activity

### ISSUE THREAD

**Issue by girum11** [tessa3/uxgraph#63]
Make sure it stays exactly between the left-side Drawer and the main Canvas, even as the page resizes.

**Comment by girum11** [comment]
Google haven't yet implemented the Angular 2 Material FAB speed dial yet:
https://github.com/angular/material2/issues/860

For now, we should just implement a straight-up FAB, no speed dial. We can punt on the speed dial part until Angular builds out their implementation.

**Comment by nati22** [comment]
I can't get the peer dependencies for [this guy](https://www.npmjs.com/package/@angular2-material/button) to work...
