### ISSUE TITLE
Clean up app file structure

### ISSUE THREAD

**Issue by nati22** [tessa3/uxgraph#7]
After creating the GAE project I simply dropped the files for the Angular 2 demo into the project without knowing how to structure the files cleanly, so at the top level there are random files that may belong to GAE or Angular. Just feels weird having all those files there. This ticket is for that discussion with @eyuelt @girum11

**Comment by girum11** [comment]
I fancy this is done now that we've chosen to go with https://github.com/mgechev/angular2-seed
