### ISSUE TITLE
Make editable multiline textbox for Card

### ISSUE THREAD

**Issue by eyuelt** [tessa3/uxgraph#86]
I need to create an editable multiline textbox that can center both vertically and horizontally in the card. Ideally the centering would be done without needing to use JS.

The options I'm looking at:
- SVG text element
  - Problem: doesn't support multiline
- Embedded HTML textarea in an SVG foreignObject
  - Problem: textarea sucks. no easy support for centering vertically
- Embedded HTML div in an SVG foreignObject with contenteditable attribute set
  - Problem: contenteditable sucks

**Comment by eyuelt** [comment]
Here's what I was trying for the textarea in a foreignObject case:
```
  <foreignObject x="0"
                 y="0"
                 attr.width="{{size.width}}"
                 attr.height="{{size.height}}">
    <xhtml:textarea xmlns="http://www.w3.org/1999/xhtml"
                    attr.width="{{size.width}}"
                    attr.height="{{size.height}}"
                    style="width: 60px; height: 80px;">
      {{card.text}}
    </xhtml:textarea>
  </foreignObject>
```

**Comment by girum11** [comment]
#88
